export enum ArticleListActionType {
  FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST',
  FETCH_ARTICLE_LIST_SUCCESS = 'FETCH_ARTICLE_LIST_success',
  FETCH_ARTICLE_LIST_ERROR = 'FETCH_ARTICLE_LIST_error'
}
